### PR TITLE
Workaround to remove `NSNull` objects in ObjC layer

### LINKED ISSUE #1185: JSON value '<null>' of type NSNull cannot be converted to NSString on React Native 0.78.0
When using react-native-purchases version ^8.6.1 in a React Native 0.78.0 project, the app crashes on a release build due to the following error:

JSON value '<null>' of type NSNull cannot be converted to NSString

Image

This issue does not occur in a React Native 0.75.5 project with the same package version.

Image

Steps to Reproduce
	1.	Create a new React Native 0.78.0 project.
	2.	Install react-native-purchases version ^8.6.1.
	3.	Run the app.
	4.	Observe the error appearing when loading react-native-purchases.
	5.	Build a release version of the app and notice that it crashes.

For comparison:
	•	React Native 0.77.1, 0.78.0 (perhaps more) → ❌ Error occurs
	•	React Native 0.75.5 → ✅ No error

Expected Behavior

The package should not cause a crash or throw this error in React Native 0.78.0.

Environment
	•	React Native version: 0.78.0
	•	react-native-purchases version: ^8.6.1
	•	Platform: iOS
	•	Build Type: Release

Additional Information

Since the error does not occur in React Native 0.75.5, it seems to be related to changes in RN 0.78.0.

Would appreciate any insights or a potential fix for this issue.

### PR DESCRIPTION
**Pull request by ajpallares**
This PR implements a workaround that fixes #1185.

With RN v0.77.1 and 0.78.0, the Objective-C layer of react-native-purchases is receiving `NSNull` objects for `null` TypeScript values (also reported in in the [RN repo](https://github.com/facebook/react-native/pull/49250#issuecomment-2668465893)).

Note that we cannot avoid the console warnings of type 
> JSON value '<null>' of type NSNull cannot be converted to NSString

Keep reading for an explanation.

## Why this was not happening in `DEBUG`

The `RCT_JSON_CONVERTER` macro is defined like this in `RCTConvert.mm` in the `React-core` dependency:

```
#if RCT_DEBUG
#define RCT_JSON_CONVERTER(type)             \
  +(type *)type : (id)json                   \
  {                                          \
    if ([json isKindOfClass:[type class]]) { \
      return json;                           \
    } else if (json) {                       \
      RCTLogConvertError(json, @ #type);     \
    }                                        \
    return nil;                              \
  }
#else
#define RCT_JSON_CONVERTER(type) \
  +(type *)type : (id)json       \
  {                              \
    return json;                 \
  }
#endif
```

In case of an unrecognized JSON object (e.g. `NSNull`), in `DEBUG`, the `RCTLogConvertError` gets printed and `nil` is returned, whereas if not `DEBUG`, the `json` object is returned **unchanged**.
With this PR, the `NSNull` get clean up.

## How I tested this

I used commit [4b369604d73564159c252483c7bf0801769eecdd](https://github.com/RevenueCat/react-native-purchases/commit/4b369604d73564159c252483c7bf0801769eecdd) to test this, as the purchasetester app in that commit already uses RN v0.78.0. With this workaround, the app crashes on iOS right after launch.

### CODE REVIEW

File: ios/RNPurchases.m [hunk 1]
```diff
@@ -592,3 +599,43 @@ - (NSString *)platformFlavorVersion {
...
+    if ([self isKindOfClass:[NSNull class]]) {
+        return nil;
+    } else if ([self isKindOfClass:NSDictionary.class]) {
+        NSMutableDictionary *filteredDict = [NSMutableDictionary dictionary];
+        NSDictionary *originalDict = (NSDictionary *)self;
+
+        for (id key in originalDict) {
+            id value = [originalDict[key] mappingNSNullToNil];
+            if (value) {
+                // Only add non-nil values to the dictionary
```
Comment (tonidero) [inline ios/RNPurchases.m:615]: Hmm I wonder if we actually want to keep the values in the dict, but just as `nil`... what do you think? (same for arrays)

**Review by tonidero — APPROVED** [review]
For the android issue, I'm increasing the machine size in my PR. 

Changes here look great! Thanks for doing this! 🙏 🙇

File: ios/RNPurchases.m (hunk 1 above)
Comment (ajpallares) [reply ios/RNPurchases.m:615]: I thought about that, but then I remembered that we're in Objective-C world. And there I believe you cannot insert `nil` into collections (I believe that might be a reason why `NSNull` exists?). The thing is:
* Setting `nil` for a key in a `NSDictionary` is used to remove the value for that key.
* Setting `nil` in an `NSArray` is not allowed.

**Review by JayShortway — APPROVED** [review]
Amazing! Thanks for doing this, and thanks for the detailed explanation! 😻 

(What do you think about [linking this PR to the issue](https://docs.github.com/en/issues/tracking-your-work-with-issues/using-issues/linking-a-pull-request-to-an-issue)?)

**Review by aboedo — APPROVED** [review]
great work on this!
