### PR TITLE
`purchasePackage`: add `StoreTransaction` in `MakePurchaseResult`

### LINKED ISSUE #659: revenueCat transactionId
- [ ] I have updated Purchases SDK to the latest version
- [ ] I have read the [Contribution Guidelines](https://github.com/RevenueCat/react-native-purchases/blob/main/CONTRIBUTING.md)
- [ ] I have searched the [Community](https://community.revenuecat.com)
- [ ] I have read [docs.revenuecat.com](https://docs.revenuecat.com/)
- [ ] I have searched for [existing Github issues](https://github.com/RevenueCat/react-native-purchases/issues)

**Describe the bug**
Not getting transactionId after successful transaction using sandBox testing,

1. Environment
   1. Platform: react Native
   2. SDK version: 5.14.0
   3. OS version: 16
   4. Xcode/Android Studio version:14.2
   5. React Native version:0.70.6
   
   import Purchases from 'react-native-purchases';
const selected = async () => {
        setIsLoading(true)
        try {
            const { customerInfo } = await Purchases.purchasePackage(packages);
            if (typeof customerInfo.entitlements.active[ENTITLEMENT_ID] !== 'undefined') {
                setIsLoading(false)
                //   addPayment(customerInfo.entitlements.active[ENTITLEMENT_ID])
                props.navigation.goBack();
            }
        } catch (e) {
            if (!e.userCancelled) {
                setIsLoading(false)
                CustomToast('info', 'Something went wrong', 'Please try again')
                console.log(e, 'e')
            }
        }

    };
    
    
    please help me i took 2 week ,despite i am unable to get transaction Id

### PR DESCRIPTION
**Pull request by NachoSoto**
See https://github.com/RevenueCat/purchases-hybrid-common/pull/685, https://github.com/RevenueCat/purchases-hybrid-common/pull/686, and https://github.com/RevenueCat/purchases-hybrid-common/pull/690.

The main changes were in those PRs. This just updates the stub data to reflect that.

Fixes #659

### CODE REVIEW

File: scripts/setupJest.js [hunk 1]
```diff
@@ -61,6 +61,11 @@ global.customerInfoStub = {
   requestDate: "2019-12-03T00:47:58.000Z",
   managementURL: "https://url.com"
 };
+global.transactionStub = {
+    productIdentifier: "com.revenuecat.purchases_hybrid_common.monthly_19.99_.1_week_intro",
+    transactionIdentifier: "1",
+    purchaseDateMilis: 1000
```
Comment (tonidero) [inline scripts/setupJest.js:67]: Hmm this doesn't add the `purchaseDate` in iso8901 format right? Might be good adding it to make sure the tests are correct?

**Review by tonidero — APPROVED** [review]

File: scripts/setupJest.js (hunk 1 above)
Comment (NachoSoto) [reply scripts/setupJest.js]: Oh you're right, fixed.
